#!/usr/bin/env node
const program = require('commander');

program
	.version('0.0.1')
	.command('generate', 'Generate default config stub')
	// .action(function(c) {
	// 	configFile = c;
	// })
program.parse(process.argv);
