#!/usr/bin/env node
try {
	let config = require('./lib/generate')(process);
	process.stdout.write(config, null, 4);
	process.exit(0);
} catch (e) {
	console.error(e);
	console.error(e.message);
	process.exit(1);
}
